[package]
name = "RustWasmRot13Base64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
rot13 = "0.1.1"

[lib]
crate-type=["cdylib"]